# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discipline', models.CharField(max_length=50)),
                ('bronze_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_medals', to='olympics.Country')),
                ('fourth_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_wins', to='olympics.Country')),
                ('gold_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_medals', to='olympics.Country')),
                ('silver_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver_medals', to='olympics.Country')),
            ],
        ),
    ]
